### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nolvade** [KitsuneLab-Development/K4-System-MMRanks#11]
Unfortunately rank its not working on new version Cssharp

**Comment by K4ryuu** [comment]
Describe your issue. “Not working” is not gonna help anything, so I will just close the issue as invalid, if no info granted. You see a good template when you open an issue, you should follow that. Also give a title to your issue.

**Comment by Cruze03** [comment]
I tested this plugin today and it works fine

**Comment by K4ryuu** [comment]
Then I close the issue. Thank you @Cruze03
