### ISSUE TITLE
[BUG] Ranks are not displaying as they should.

### ISSUE THREAD

**Issue by SubCoderHUN** [KitsuneLab-Development/K4-System-MMRanks#12]
**Describe the bug**
The ranks are not showing correctly. All players can see some ranks, but not for all and not for a specific player. It's random what players sees what.
For example:
There are 5 players.

p1 sees p2 and p5.
p2 sees p4 and p2.
p3 sees p1 and p2 and p4.

**To Reproduce**
1. Install K4-System
2. Install K4-System-MMRanks
3. See error

**Expected behavior**
Show the ranks for all players.

**Media (Optional)**

**Logs (Optional)**

**Additional context (Optional)**

**Comment by K4ryuu** [comment]
Read the ReadMe of the repository.
