### ISSUE TITLE
[BUG] Inconsistent Display of Scoreboard Rank Images

### ISSUE THREAD

**Issue by Mesharsky** [KitsuneLab-Development/K4-System-MMRanks#2]
**Describe the bug**

In a plugin designed to show scoreboard rank images next to player names, the images are inconsistently displayed. While it is expected that every player's scoreboard rank image is shown, the plugin only displays these images for a subset of players at any given time, typically only 1 to 3 players. This issue persists despite using the latest versions of CSS, metamod, and the K4 system plugin.

**To Reproduce**

Steps to reproduce the behavior are not specific, as the issue seems to occur randomly during gameplay. But you will never have all images for all players shown

**Expected behavior**

The expected behavior is for every player's scoreboard rank image to be displayed next to their name on the scoreboard, without exceptions. This should be consistent across all players and instances, ensuring that everyone's rank is visually represented as intended by the plugin.

**Comment by Cruze03** [comment]
[fakeranks.zip](https://github.com/K4ryuu/K4-System-MMRanks/files/14932864/fakeranks.zip)
Try this. Code yoinked from Pisex's fake ranks

**Comment by Mesharsky** [comment]
> [fakeranks.zip](https://github.com/K4ryuu/K4-System-MMRanks/files/14932864/fakeranks.zip) Try this. Code yoinked from Pisex's fake ranks

That's eventually crashing the server unfortunately.
Unless it's not compatible with cs2fixes

**Comment by Cruze03** [comment]
I use the same in my server. Seems to work fine for me without crash. You can DM me on discord and tell me at what time server is crashing

**Comment by Mesharsky** [comment]
Send your dc please

**Comment by Cruze03** [comment]
Discord: cruze03

**Comment by Cruze03** [comment]
https://github.com/Cruze03/FakeRanks-RevealAll/releases/latest
