### ISSUE TITLE
[BUG] crash when I change the map

### ISSUE THREAD

**Issue by russh3l** [KitsuneLab-Development/K4-System-MMRanks#8]
crash when I change the map
 
 metamod 1290
 css 233

**Comment by K4ryuu** [comment]
What makes you think its from this plugin?

**Comment by K4ryuu** [comment]
The version that I just posted is going to block rank updates between match panel and next map warmup start, so this plugin is impossible to cause any problem on map changes anymore. The full plugin is being disabled between those two.
